// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export default function Card3(props: any) {
  const { nodes, materials } = useGLTF("/card_model3.glb");
  return (
    <motion.group
      {...props}
      dispose={null}
      // animate={{ rotateY: Math.PI }}
      // transition={{ ease: "linear", duration: 0.6 }}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CardBack.geometry}
        material={materials.gothai}
        position={[0, 1.11, 0]}
        scale={[0.57, 0.94, 0.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CardFront.geometry}
        material={materials.image24}
        position={[0, 1.11, -0.07]}
        scale={[0.57, 0.94, 0.1]}
      />
    </motion.group>
  );
}

useGLTF.preload("/card_model3.glb");
