/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LostBoyz2078 (https://sketchfab.com/LostModels2025)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/eye-df0f03d48b484f73869f0cff88272e4d
Title: Eye
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { motion } from "framer-motion-3d";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/eye.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      // Play a specific animation or all animations
      // Example: actions['AnimationName'].play();
      // To play all animations:
      Object.values(actions).forEach((action) => {
        // console.log(action);
        action.play();
      });
    }
  }, [actions]);

  return (
    <motion.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="GLTF_created_0">
                <primitive object={nodes.GLTF_created_0_rootJoint} />
                <skinnedMesh
                  name="Object_7"
                  geometry={nodes.Object_7.geometry}
                  material={materials.ML1010_A_MATb_MI}
                  skeleton={nodes.Object_7.skeleton}
                />
                <skinnedMesh
                  name="Object_10"
                  geometry={nodes.Object_10.geometry}
                  material={materials.ML1010_A_MATa}
                  skeleton={nodes.Object_10.skeleton}
                />
                <group name="0000_ML1010_SK_00_21">
                  <group name="0000_ML1010_SK_00_22" />
                </group>
                <group name="0001_ML1010_SK_00_23">
                  <group name="0001_ML1010_SK_00_24" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </motion.group>
  );
}

useGLTF.preload("/models/eye.glb");
